<?php
use App\Http\Controllers\{AuthController,FleetController}; use Illuminate\Support\Facades\Route;
Route::post('/login',[AuthController::class,'login']);
Route::middleware('jwt')->group(function(){
 Route::post('/logout',[AuthController::class,'logout']); Route::get('/me',[AuthController::class,'me']);
 Route::get('/solicitudes',[FleetController::class,'requests']); Route::post('/solicitudes',[FleetController::class,'requestStore'])->middleware('role:SOLICITANTE'); Route::get('/solicitudes/pendientes',[FleetController::class,'pending'])->middleware('role:COORDINADOR,ADMINISTRADOR'); Route::get('/solicitudes/{id}',[FleetController::class,'requestShow']);
 Route::patch('/solicitudes/{id}/aprobar',fn($id,\Illuminate\Http\Request $r)=>app(FleetController::class)->requestStatus($r,$id,'Evaluada'))->middleware('role:COORDINADOR'); Route::patch('/solicitudes/{id}/rechazar',fn($id,\Illuminate\Http\Request $r)=>app(FleetController::class)->requestStatus($r,$id,'Cancelada'))->middleware('role:COORDINADOR');
 Route::get('/vehiculos',[FleetController::class,'vehicles']); Route::get('/vehiculos/disponibles',fn(\Illuminate\Http\Request $r)=>app(FleetController::class)->vehicles($r->merge(['available'=>true]))); Route::post('/vehiculos',[FleetController::class,'vehicleSave'])->middleware('role:COORDINADOR,ADMINISTRADOR'); Route::put('/vehiculos/{id}',[FleetController::class,'vehicleSave'])->middleware('role:COORDINADOR,ADMINISTRADOR'); Route::patch('/vehiculos/{id}/estado',[FleetController::class,'vehicleStatus'])->middleware('role:COORDINADOR,ADMINISTRADOR');
 Route::get('/conductores',[FleetController::class,'drivers']); Route::get('/conductores/disponibles',fn(\Illuminate\Http\Request $r)=>app(FleetController::class)->drivers($r->merge(['available'=>true]))); Route::post('/conductores',[FleetController::class,'driverSave'])->middleware('role:COORDINADOR,ADMINISTRADOR'); Route::put('/conductores/{id}',[FleetController::class,'driverSave'])->middleware('role:COORDINADOR,ADMINISTRADOR'); Route::patch('/conductores/{id}/estado',[FleetController::class,'driverStatus'])->middleware('role:COORDINADOR,ADMINISTRADOR');
 Route::post('/programacion',[FleetController::class,'schedule'])->middleware('role:COORDINADOR'); Route::get('/programacion',[FleetController::class,'assignments'])->middleware('role:COORDINADOR,ADMINISTRADOR'); Route::get('/programacion/{id}',[FleetController::class,'assignment']);
 Route::get('/conductor/rutas',[FleetController::class,'driverRoutes'])->middleware('role:CONDUCTOR'); Route::get('/conductor/hoja-ruta/{id}',[FleetController::class,'assignment'])->middleware('role:CONDUCTOR,COORDINADOR'); Route::post('/kilometraje',[FleetController::class,'mileage'])->middleware('role:CONDUCTOR'); Route::patch('/conductor/finalizar-servicio/{id}',[FleetController::class,'finish'])->middleware('role:CONDUCTOR');
 Route::get('/dashboard/resumen',[FleetController::class,'dashboard']); Route::get('/dashboard/vehiculos',[FleetController::class,'dashboard']); Route::get('/dashboard/servicios-mensuales',[FleetController::class,'dashboard']); Route::get('/auditoria',[FleetController::class,'audits'])->middleware('role:ADMINISTRADOR');
});
