CREATE DATABASE GestionFlota; GO
USE GestionFlota; GO
CREATE TABLE roles(id BIGINT IDENTITY PRIMARY KEY,nombre VARCHAR(30) NOT NULL UNIQUE,descripcion VARCHAR(200),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE areas(id BIGINT IDENTITY PRIMARY KEY,nombre VARCHAR(100) NOT NULL UNIQUE,created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE empleados(id BIGINT IDENTITY PRIMARY KEY,area_id BIGINT NOT NULL REFERENCES areas(id),dni CHAR(8) NOT NULL UNIQUE,nombre_completo VARCHAR(150) NOT NULL,cargo VARCHAR(100) NOT NULL,telefono VARCHAR(20),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE usuarios(id BIGINT IDENTITY PRIMARY KEY,rol_id BIGINT NOT NULL REFERENCES roles(id),empleado_id BIGINT NULL REFERENCES empleados(id),nombre VARCHAR(150) NOT NULL,email VARCHAR(150) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,activo BIT DEFAULT 1,created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE solicitudes_vehiculares(id BIGINT IDENTITY PRIMARY KEY,codigo_solicitud VARCHAR(30) NOT NULL UNIQUE,empleado_id BIGINT NOT NULL REFERENCES empleados(id),punto_origen VARCHAR(200) NOT NULL,punto_destino VARCHAR(200) NOT NULL,fecha_servicio DATE NOT NULL,hora_requerida TIME NOT NULL,cantidad_pasajeros SMALLINT NOT NULL CHECK(cantidad_pasajeros>0),motivo VARCHAR(MAX) NOT NULL,fecha_registro DATETIME2 NOT NULL,estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente' CHECK(estado IN('Pendiente','Evaluada','Programada','Atendida','Cancelada')),sujeta_disponibilidad BIT NOT NULL DEFAULT 0,motivo_rechazo VARCHAR(500),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE vehiculos(id BIGINT IDENTITY PRIMARY KEY,placa VARCHAR(10) NOT NULL UNIQUE,marca VARCHAR(80) NOT NULL,modelo VARCHAR(80) NOT NULL,anio SMALLINT NOT NULL,capacidad_pasajeros SMALLINT NOT NULL CHECK(capacidad_pasajeros>0),tipo_vehiculo VARCHAR(50) NOT NULL,estado VARCHAR(20) NOT NULL CHECK(estado IN('Disponible','Asignado','En ruta','Mantenimiento','Inoperativo')),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE conductores(id BIGINT IDENTITY PRIMARY KEY,usuario_id BIGINT NULL REFERENCES usuarios(id),dni CHAR(8) NOT NULL UNIQUE,nombre_completo VARCHAR(150) NOT NULL,licencia VARCHAR(30) NOT NULL UNIQUE,categoria VARCHAR(20) NOT NULL,telefono VARCHAR(20),estado VARCHAR(20) NOT NULL CHECK(estado IN('Disponible','Ocupado','Descanso')),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE asignaciones_vehiculares(id BIGINT IDENTITY PRIMARY KEY,solicitud_id BIGINT NOT NULL UNIQUE REFERENCES solicitudes_vehiculares(id),vehiculo_id BIGINT NOT NULL REFERENCES vehiculos(id),conductor_id BIGINT NOT NULL REFERENCES conductores(id),inicio DATETIME2 NOT NULL,fin DATETIME2 NOT NULL,estado VARCHAR(20) NOT NULL CHECK(estado IN('Programada','En ruta','Atendida','Cancelada')),CHECK(fin>inicio),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE rutas(id BIGINT IDENTITY PRIMARY KEY,asignacion_id BIGINT NOT NULL UNIQUE REFERENCES asignaciones_vehiculares(id),origen VARCHAR(200),destino VARCHAR(200),indicaciones VARCHAR(MAX),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE detalle_rutas(id BIGINT IDENTITY PRIMARY KEY,ruta_id BIGINT NOT NULL REFERENCES rutas(id),secuencia SMALLINT NOT NULL,lugar VARCHAR(200) NOT NULL,observacion VARCHAR(500),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE comisiones_servicio(id BIGINT IDENTITY PRIMARY KEY,asignacion_id BIGINT NOT NULL REFERENCES asignaciones_vehiculares(id),numero_documento VARCHAR(40),descripcion VARCHAR(MAX),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE salidas_vehiculo(id BIGINT IDENTITY PRIMARY KEY,asignacion_id BIGINT NOT NULL REFERENCES asignaciones_vehiculares(id),fecha_salida DATETIME2 NOT NULL,kilometraje_inicial DECIMAL(12,2) NOT NULL,created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE retornos_vehiculo(id BIGINT IDENTITY PRIMARY KEY,asignacion_id BIGINT NOT NULL REFERENCES asignaciones_vehiculares(id),fecha_retorno DATETIME2 NOT NULL,kilometraje_final DECIMAL(12,2) NOT NULL,created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE kilometrajes(id BIGINT IDENTITY PRIMARY KEY,asignacion_id BIGINT NOT NULL UNIQUE REFERENCES asignaciones_vehiculares(id),inicial DECIMAL(12,2),final DECIMAL(12,2),CHECK(final IS NULL OR inicial IS NULL OR final>=inicial),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
CREATE TABLE auditoria(id BIGINT IDENTITY PRIMARY KEY,usuario_id BIGINT NULL REFERENCES usuarios(id),accion VARCHAR(60) NOT NULL,entidad VARCHAR(60) NOT NULL,entidad_id BIGINT,detalle NVARCHAR(MAX),ip VARCHAR(45),created_at DATETIME2 DEFAULT SYSDATETIME(),updated_at DATETIME2 DEFAULT SYSDATETIME());
GO
CREATE INDEX IX_asignacion_vehiculo_horario ON asignaciones_vehiculares(vehiculo_id,inicio,fin); CREATE INDEX IX_asignacion_conductor_horario ON asignaciones_vehiculares(conductor_id,inicio,fin); GO
INSERT roles(nombre) VALUES('ADMINISTRADOR'),('COORDINADOR'),('CONDUCTOR'),('SOLICITANTE'); INSERT areas(nombre) VALUES('Administración'),('Operaciones'); INSERT vehiculos(placa,marca,modelo,anio,capacidad_pasajeros,tipo_vehiculo,estado) VALUES('ABC-123','Toyota','Hilux',2024,5,'Camioneta','Disponible'); GO
CREATE TRIGGER trg_retorno_disponible ON retornos_vehiculo AFTER INSERT AS UPDATE v SET estado='Disponible',updated_at=SYSDATETIME() FROM vehiculos v JOIN asignaciones_vehiculares a ON a.vehiculo_id=v.id JOIN inserted i ON i.asignacion_id=a.id; GO
