<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration { public function up():void {
 Schema::dropIfExists('users');
 Schema::create('roles',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->string('description')->nullable(),$t->timestamps()]);
 Schema::create('areas',fn(Blueprint $t)=>[$t->id(),$t->string('name')->unique(),$t->timestamps()]);
 Schema::create('employees',fn(Blueprint $t)=>[$t->id(),$t->foreignId('area_id')->constrained(),$t->string('dni',8)->unique(),$t->string('full_name'),$t->string('position'),$t->string('phone',20),$t->timestamps()]);
 Schema::create('users',fn(Blueprint $t)=>[$t->id(),$t->foreignId('role_id')->constrained(),$t->foreignId('employee_id')->nullable()->constrained(),$t->string('name'),$t->string('email')->unique(),$t->timestamp('email_verified_at')->nullable(),$t->string('password'),$t->boolean('active')->default(true),$t->rememberToken(),$t->timestamps()]);
 Schema::create('vehicle_requests',fn(Blueprint $t)=>[$t->id(),$t->string('code')->unique(),$t->foreignId('employee_id')->constrained(),$t->string('origin'),$t->string('destination'),$t->date('service_date'),$t->time('required_time'),$t->unsignedSmallInteger('passenger_count'),$t->text('reason'),$t->dateTime('registered_at'),$t->string('status')->default('Pendiente'),$t->boolean('subject_to_availability')->default(false),$t->text('rejection_reason')->nullable(),$t->timestamps()]);
 Schema::create('vehicles',fn(Blueprint $t)=>[$t->id(),$t->string('plate',10)->unique(),$t->string('brand'),$t->string('model'),$t->unsignedSmallInteger('year'),$t->unsignedSmallInteger('passenger_capacity'),$t->string('vehicle_type'),$t->string('status')->default('Disponible'),$t->timestamps()]);
 Schema::create('drivers',fn(Blueprint $t)=>[$t->id(),$t->foreignId('user_id')->nullable()->constrained(),$t->string('dni',8)->unique(),$t->string('full_name'),$t->string('license')->unique(),$t->string('category'),$t->string('phone',20),$t->string('status')->default('Disponible'),$t->timestamps()]);
 Schema::create('assignments',fn(Blueprint $t)=>[$t->id(),$t->foreignId('vehicle_request_id')->unique()->constrained('vehicle_requests'),$t->foreignId('vehicle_id')->constrained(),$t->foreignId('driver_id')->constrained(),$t->dateTime('starts_at'),$t->dateTime('ends_at'),$t->string('status')->default('Programada'),$t->timestamps()]);
 Schema::create('routes',fn(Blueprint $t)=>[$t->id(),$t->foreignId('assignment_id')->unique()->constrained(),$t->string('origin'),$t->string('destination'),$t->text('instructions')->nullable(),$t->timestamps()]);
 Schema::create('route_details',fn(Blueprint $t)=>[$t->id(),$t->foreignId('route_id')->constrained('routes'),$t->unsignedSmallInteger('sequence'),$t->string('place'),$t->text('observation')->nullable(),$t->timestamps()]);
 Schema::create('service_commissions',fn(Blueprint $t)=>[$t->id(),$t->foreignId('assignment_id')->constrained(),$t->string('document_number')->nullable(),$t->text('description'),$t->timestamps()]);
 Schema::create('vehicle_departures',fn(Blueprint $t)=>[$t->id(),$t->foreignId('assignment_id')->constrained(),$t->dateTime('departed_at'),$t->decimal('initial_mileage',12,2),$t->timestamps()]);
 Schema::create('vehicle_returns',fn(Blueprint $t)=>[$t->id(),$t->foreignId('assignment_id')->constrained(),$t->dateTime('returned_at'),$t->decimal('final_mileage',12,2),$t->timestamps()]);
 Schema::create('mileages',fn(Blueprint $t)=>[$t->id(),$t->foreignId('assignment_id')->constrained(),$t->decimal('initial',12,2)->nullable(),$t->decimal('final',12,2)->nullable(),$t->timestamps()]);
 Schema::create('system_parameters',fn(Blueprint $t)=>[$t->id(),$t->string('key')->unique(),$t->text('value'),$t->timestamps()]);
 Schema::create('audit_logs',fn(Blueprint $t)=>[$t->id(),$t->foreignId('user_id')->nullable()->constrained(),$t->string('action'),$t->string('entity'),$t->unsignedBigInteger('entity_id')->nullable(),$t->json('details')->nullable(),$t->string('ip',45)->nullable(),$t->timestamps()]);
 } public function down():void { foreach(['audit_logs','system_parameters','mileages','vehicle_returns','vehicle_departures','service_commissions','route_details','routes','assignments','drivers','vehicles','vehicle_requests','users','employees','areas','roles'] as $x)Schema::dropIfExists($x); } };
